// Shared mapping of Assignment IDs to their definition files
// Used by both inleveren.html (rubric snapshot) and grading-ui.js (grading modal)
const ASSIGNMENT_MAP = {
    "A3": "opdrachten/portfoliostartopdracht_a3.html",
    "A2": "opdrachten/a2_communiceren.html",
    "A5": "opdrachten/a5_onderzoeken.html",
    "F2": "opdrachten/f2_maatschappij.html",
    "A4": "opdrachten/a4_orienteren.html",
    "A1": "opdrachten/a1_informatievaardigheden.html",
    "A7": "opdrachten/a7_waarderen.html",
    "E2": "opdrachten/e2_security.html",
    "F4": "opdrachten/f4_security.html",
    "F3": "opdrachten/f3_privacy.html",
    "ModIntro": "opdrachten/modintro_leren_modelleren.html",
    "A6": "opdrachten/a6_modelleren.html",
    "C5": "opdrachten/c5_gestructureerde_data.html",
    "C1": "opdrachten/c1_warming_stripes.html",
    "C2": "opdrachten/c2_identificeren.html",
    "B3": "opdrachten/b3_automaten.html",
    "B1": "opdrachten/b1_algoritme.html",
    "B2": "opdrachten/b2_datastructuren.html",
    "C3": "opdrachten/c3_representeren.html",
    "D1": "opdrachten/d1_ontwikkelen.html",
    "D2": "opdrachten/d2_inspecteren.html",
    "B4": "opdrachten/b4_introductie_html.html",
    "F1": "opdrachten/f1_usability.html",
    "C4": "opdrachten/c4_standaard_representaties.html",
    "E1": "opdrachten/e1_decompositie.html",
    "Eind1": "opdrachten/eindopdracht_gamedev.html",
    "Eind2": "opdrachten/eindopdracht_webshop.html",
    "Eind3": "opdrachten/eindopdracht_encryptie.html"
};

const ASSIGNMENT_TITLES = {
    "A3": "Portfoliostartopdracht",
    "A2": "Communiceren",
    "A5": "Onderzoeken",
    "F2": "Maatschappelijke aspecten",
    "A4": "Orienteren op studie/beroep",
    "A1": "Informatievaardigheden",
    "A7": "Waarderen en oordelen",
    "E2": "Security (Algemeen)",
    "F4": "Security (Wachtwoorden)",
    "F3": "Privacy",
    "ModIntro": "Leren Modelleren (Intro)",
    "A6": "Modelleren",
    "C5": "Gestructureerde data",
    "C1": "Warming Stripes",
    "C2": "Identificeren",
    "B3": "Automaten",
    "B1": "Algoritme",
    "B2": "Datastructuren",
    "C3": "Representeren",
    "D1": "Ontwikkelen",
    "D2": "Inspecteren en aanpassen",
    "B4": "Introductie HTML",
    "F1": "Usability",
    "C4": "Standaard representaties",
    "E1": "Decompositie",
    "Eind1": "Game Development",
    "Eind2": "Webshop",
    "Eind3": "Encryptie"
};
